### ISSUE TITLE
JAMPRED_Examples.R failed

### ISSUE THREAD

**Issue by phelkkula** [pjnewcombe/R2BGLiMS#11]
I tried running the JAMPRED_Examples.R script (R version 3.6.0) but got the following error:

Taking inverse of xTx...
  block 1/1 inverted
...inverse calculated
Error in FUN(X[[i]], ...) : 
  trying to get slot "posterior.summary.table" from an object of a basic class ("character") with no slots
Calls: JAMPred -> unlist -> lapply -> FUN
In addition: Warning message:
In mclapply(c(1:n.cores), function(i) JAM(marginal.betas = marginal.betas[unlist(snps.blocks[parallel.block.indices[[i]]])],  :
  scheduled cores 28 encountered errors in user code, all values of the jobs will be affected
Execution halted

**Comment by pjnewcombe** [comment]
Hi there,

Very sorry about this and thank you for letting me know. 

A post-release bug which produced a similar error, was fixed a week or two ago in the last commit. Could I verify you are running the very latest version from GitHub?

If so, would you mind please emailing me the JAMPRED_Example.R script you are running to paul.newcombe@mrc-bsu.cam.ac.uk? Sometimes there are issues from copying the code from the supplemental PDF. Also is it on Windows, Mac or Linux?

Thanks,
Paul

**Comment by phelkkula** [comment]
Hi Paul,
I cloned this repo a few days ago and tried running the 'JAMPRED_Examples.R' script in R2BGLiMS/Examples. I have a Linux system.
Thank you,
Pyry

**Comment by pjnewcombe** [comment]
I think we figured this out - so marking as closed. Just let me know if it recurs!

**Comment by kulmsc** [comment]
I am still receiving an identical error.  I am running version 0.1-07-02-2020.

The code I am running is:

`
library(R2BGLiMS)
data("JAMPred_Example")

snps <- chromosome.snps[[1]] # Only use chromosome 1 data
jampred.res.bin <- JAMPred(
 marginal.betas = marginal.logors[snps],
 n.training = n.training,
 marginal.logor.ses = marginal.logor.ses, # Only necessary for a binary trait
 p.cases.training = n.cases.training/n.training, # Only necessary for a binary trait
 ref.geno = data.validation[,snps],
 total.snps.genome.wide = 500000, # Total SNPs across all chromosomes
 n.mil = 0.2,
 seed = 1 # For re-producibility. If not set a random seed is used
)
`

**Comment by pjnewcombe** [comment]
Hi there,

I’m afraid I don’t get an error running the code below using the latest version, on my laptop (a Mac).

Can you tell me what the error is?

Also - you said “I am still receiving an identical error”. I wasn’t quite sure what this referred to? (perhaps my GitHub messages aren’t coming through).

Thank you for trying JAMPred.

Paul

**Comment by kulmsc** [comment]
Paul,

Thank you for the fast reply.

Sorry for the previous unclear message.  IThe error that I am receiving is:

Error in FUN(X[[i]], ...) :
trying to get slot "posterior.summary.table" from an object of a basic class ("character") with no slots
Calls: JAMPred -> unlist -> lapply -> FUN
In addition: Warning message:
In mclapply(c(1:n.cores), function(i) JAM(marginal.betas = marginal.betas[unlist(snps.blocks[parallel.block.indices[[i]]])], :
scheduled cores 28 encountered errors in user code, all values of the jobs will be affected
Execution halted

I have just installed R2BGLiMS on my local laptop (running Ubuntu) and have been able to successfully execute the example.  However on my academic computing system I am still unable.  The version of R2BGLiMS is the same on both, and both are running R 3.6 .  Could the error perhaps be based on the version of Java?  The Java on the academic computer seems rather old (specifically 1.8.0_92).  I can alternatively supply my full sessionInfo() if it would be of help.

Thank you,
Scott

**Comment by pjnewcombe** [comment]
Hi there Scott,

Thanks for the below. One suggestion would be trying to manually set the option: n.cores

Could try just setting it to 2 to begin with - for testing, and then increasing according to what should be available on your cluster. I’ve seen this sort of error before when the (far from perfect) JAMPred logic gets the number of CPU cores available wrong.

Let me know if that helps...
Paul
